### ISSUE TITLE
menu_items is an empty list

### ISSUE THREAD

**Issue by confuzeus** [jazzband/wagtailmenus#364]
I added items to my main menu and when I query `MainMenuItem`, it properly returns a queryset of all my `MainMenuItem` objects.

However, in my custom template, the `menu_items` context is an empty list. What's causing this?

EDIT: The menu_items context is empty even when using default templates.

**Comment by Allan-Nava** [comment]
Same error +1

**Comment by ababic** [comment]
Hey @confuzeus / @Allan-Nava. Are your menu items linking to pages or custom urls? And are those pages all published and have a `True` value for `show_in_menus`?

**Comment by confuzeus** [comment]
Hi @ababic, Items are linking to regular pages and show_in_menus is true.

**Comment by Allan-Nava** [comment]
> Hi @ababic, Items are linking to regular pages and show_in_menus is true.

Me too

**Comment by ababic** [comment]
I'm afraid I'm unable to reproduce this issue as described. 

I followed these instructions to create a fresh wagtailmenus dev environment, loaded in the test fixtures, and everything worked as expected (with Django 3.0.6 + Wagtail 2.8.2):
https://wagtailmenus.readthedocs.io/en/stable/contributing/index.html#developing-locally

Can you provide any additional information that might help me recreate? For example, are you overriding menu/menu item models? Are you overriding any other defaults with settings?

**Comment by confuzeus** [comment]
It looks like the issue is present only on Django 3.0. On 2.2 everything works as expected.

**Comment by shinchan28** [comment]
I am trying to add "Handle" slugfield with "allow_unicode=True" and modified the Flatmenu. It got updated fine and i am able to add flat menus. we have been using get_top_level_items() to fetch the values to navigate in Homepage but it is returning empty. I am unable to see the headings on my Homepage. Kindly let me know if you need more details

**Comment by ababic** [comment]
@confuzeus @Allan-Nava or anyone else experiencing this issue, it would be super helpful if you could specify:

- Which type of menu you are having the problem with
- Whether you are using a custom menu model/class
- Whether you are using a custom menu item model/class
- Whether you are using the built-in menu tags or generating the menus some other way
- What wagtailmenus-specific settings you have overridden for your project

**Comment by ababic** [comment]
I am still unable to reduce this error as reported with Django 3.0.6 + Wagtail 2.8.2, having followed the instructions from the docs. If you are absolutely sure that the problem is with wagtailmenus, and not your implementation, I am happy to investigate further, but I'll need to know far more information than has been provided so far. 

To help rule out an issue with wagtailmenus, please try the following steps. 

1. Follow these instructions to set up a local development environment with virtualenv:
https://wagtailmenus.readthedocs.io/en/stable/contributing/index.html#developing-locally
2. In the `development` app, add a `models.py` file and paste in the lines from the example at the end of this comment.
3. From the command line, run: `python manage.py makemigrations development`
4. Run: `python manage.py migrate development`
5. Run `python mange.py runserver`
6. Add the two lines from the example below to `wagtailmenus/settings/development.py`
7. In your browser, access the wagtail admin area using your superuser credentials
8. From the left menu, select **Settings > Main menu** (you'll see the custom 'Number' field at the top, and you should also see the custom 'String' field for each menu item)
9. Populate the menu (for the default site), selecting a few top-level pages for menu items, and adding some custom url items for good measure
10. From the left menu, select **Settings > Flat menu**, then click the 'Create' button at the top of the listing. (Again, you'll see the custom 'Number' field at the top, and you should also see the custom 'String' field for each menu item.)
11.  Create a menu for the default site using the `footer` handle, selecting a few of the top-level pages for menu items and adding some custom url items for good measure.
12. View the home page for the front end of the site (`e.g. http://127.0.0.1:8000/`

You should see multiple versions of the main menu of the top of the page, with the custom menu items showing correctly.

At the very bottom of the page, you should also see 2 versions of the `footer` flat menu rendered, again, with custom menu items showing correctly.


6. Type


### settings/development.py

```
WAGTAILMENUS_FLAT_MENU_MODEL = 'development.CustomFlatMenu'
WAGTAILMENUS_MAIN_MENU_MODEL = 'development.CustomMainMenu'
```

### development/models.py
 ```
from django.db import models

from modelcluster.fields import ParentalKey

from wagtail.admin.edit_handlers import FieldPanel
from wagtailmenus.conf import settings
from wagtailmenus.models import (
    AbstractMainMenu, AbstractMainMenuItem,
    AbstractFlatMenu, AbstractFlatMenuItem
)


class CustomMainMenu(AbstractMainMenu):
    number = models.IntegerField(blank=True, null=True)
    content_panels = [FieldPanel('number')] + list(AbstractMainMenu.content_panels)


class CustomFlatMenu(AbstractFlatMenu):
    number = models.IntegerField(blank=True, null=True)
    content_panels = [FieldPanel('number')] + list(AbstractFlatMenu.content_panels)


class CustomFlatMenuItem(AbstractFlatMenuItem):
    string = models.CharField(max_length=255)
    menu = ParentalKey(
        CustomFlatMenu,
        on_delete=models.CASCADE,
        related_name=settings.FLAT_MENU_ITEMS_RELATED_NAME
    )
    link_page = models.ForeignKey(
        'wagtailcore.Page',
        verbose_name='link to page',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='+'
    )
    panels = [FieldPanel('string')] + list(AbstractFlatMenuItem.panels)


class CustomMainMenuItem(AbstractMainMenuItem):
    string = models.CharField(max_length=255)
    menu = ParentalKey(
        CustomMainMenu,
        on_delete=models.CASCADE,
        related_name=settings.MAIN_MENU_ITEMS_RELATED_NAME
    )
    link_page = models.ForeignKey(
        'wagtailcore.Page',
        verbose_name='link to an internal page',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='+'
    )
    panels = [FieldPanel('string')] + list(AbstractMainMenuItem.panels)
```

**Comment by ababic** [comment]
@shinchan28 Please can you try copying and pasting the above models into your project and see if things work for you after changing the settings as specified? (you don't have to delete your existing models - they can happily live alongside each other)

**Comment by shinchan28** [comment]
I have did the exact on my local env by and we are running the application on docker. My application is getting exited with code 3.

**Code:**
from django.db import models
from django.utils.translation import ugettext_lazy as _
from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel, MultiFieldPanel
from django.utils import translation
from wagtailmenus.conf import settings
from wagtailmenus.panels import FlatMenuItemsInlinePanel
from wagtailmenus.models import (
   AbstractMainMenu, AbstractMainMenuItem,
   AbstractFlatMenu, AbstractFlatMenuItem
)


class CustomMainMenu(AbstractMainMenu):
   number = models.IntegerField(blank=True, null=True)
   content_panels = [FieldPanel('number')] + list(AbstractMainMenu.content_panels)


class CustomFlatMenu(AbstractFlatMenu):
   number = models.IntegerField(blank=True, null=True)
   content_panels = [FieldPanel('number')] + list(AbstractFlatMenu.content_panels)


class CustomFlatMenuItem(AbstractFlatMenuItem):
   string = models.CharField(max_length=255)
   menu = ParentalKey(
       CustomFlatMenu,
       on_delete=models.CASCADE,
       related_name=settings.FLAT_MENU_ITEMS_RELATED_NAME
   )
   link_page = models.ForeignKey(
       'wagtailcore.Page',
       verbose_name='link to page',
       blank=True,
       null=True,
       on_delete=models.CASCADE,
       related_name='+'
   )
   panels = [FieldPanel('string')] + list(AbstractFlatMenuItem.panels)


class CustomMainMenuItem(AbstractMainMenuItem):
   string = models.CharField(max_length=255)
   menu = ParentalKey(
       CustomMainMenu,
       on_delete=models.CASCADE,
       related_name=settings.MAIN_MENU_ITEMS_RELATED_NAME
   )
   link_page = models.ForeignKey(
       'wagtailcore.Page',
       verbose_name='link to page',
       blank=True,
       null=True,
       on_delete=models.CASCADE,
       related_name='+'
   )
   panels = [FieldPanel('string')] + list(AbstractMainMenuItem.panels)



**Dev.py**
WAGTAILMENUS_FLAT_MENU_MODEL = "main.CustomFlatMenu"
WAGTAILMENUS_MAIN_MENU_MODEL = "main.CustomMainMenu"

**Comment by shinchan28** [comment]
@ababic

**Comment by shinchan28** [comment]
@ababic please let me know if need more details

**Comment by shinchan28** [comment]
I have tried the same in my local environment with adding customMainmenu as per the above. Wagtail admin page is loading fine and i am able to enter the values in the fields as well, but the values are not passing to front end and my Homepage heading is empty

Please find the following code attached,

**development.py**

from django.db import models
from django.utils.translation import ugettext_lazy as _
from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import FieldPanel, PageChooserPanel, MultiFieldPanel
from django.utils import translation
from wagtailmenus.conf import settings
from wagtailmenus.panels import FlatMenuItemsInlinePanel
from wagtailmenus.models import (
   AbstractMainMenu, AbstractMainMenuItem,
   AbstractFlatMenu, AbstractFlatMenuItem
)


class CustomMainMenu(AbstractMainMenu):
    number = models.IntegerField(blank=True, null=True)
    content_panels = [FieldPanel('number')] + list(AbstractMainMenu.content_panels)


class CustomFlatMenu(AbstractFlatMenu):
    handle = models.SlugField(
        verbose_name=_('handle'),
        allow_unicode=True,
        max_length=255,
        help_text=_("enter slug")
    )

    # Like pages, panels for menus are split into multiple tabs.
    # To update the panels in the 'Content' tab, override 'content_panels'
    # To update the panels in the 'Settings' tab, override 'settings_panels'
    content_panels = (
        MultiFieldPanel(
            heading=_("MENU DETAILS"),
            children=(
                FieldPanel("title"),
                FieldPanel("site"),
                FieldPanel("handle"),
                FieldPanel("heading")
            ),
        ),
        FlatMenuItemsInlinePanel(),
    )


class CustomFlatMenuItem(AbstractFlatMenuItem):
    menu = ParentalKey(
       CustomFlatMenu,
       on_delete=models.CASCADE,
       related_name=settings.FLAT_MENU_ITEMS_RELATED_NAME
    )
    link_page = models.ForeignKey(
       'wagtailcore.Page',
       verbose_name='link to page',
       blank=True,
       null=True,
       on_delete=models.CASCADE,
       related_name='+'
    )
    hover_description = models.TextField(
        blank=True,
        help_text=_(
            "Provide the text to use for showing as description while showing child links"
        ))

    open_in_new_window = models.BooleanField(default=False)

    # Also override the panels attribute, so that the new fields appear
    # in the admin interface
    panels = (
        PageChooserPanel('link_page'),
        FieldPanel('link_url'),
        FieldPanel('url_append'),
        FieldPanel('link_text'),
        FieldPanel('hover_description'),
        FieldPanel('open_in_new_window'),
    )


class CustomMainMenuItem(AbstractMainMenuItem):
    string = models.CharField(max_length=255)
    menu = ParentalKey(
       CustomMainMenu,
       on_delete=models.CASCADE,
       related_name=settings.MAIN_MENU_ITEMS_RELATED_NAME
    )
    link_page = models.ForeignKey(
       'wagtailcore.Page',
       verbose_name='link to page',
       blank=True,
       null=True,
       on_delete=models.CASCADE,
       related_name='+'
    )
    panels = [FieldPanel('string')] + list(AbstractMainMenuItem.panels)


**settings.py**
WAGTAILMENUS_FLAT_MENU_MODEL = "main.CustomFlatMenu"
WAGTAILMENUS_MAIN_MENU_MODEL = "main.CustomMainMenu"

**wagtail_settings.py**

    def get_menu_items(self, menu_handle):
        
        items = []
        menuItems = []
        try:
            menu = FlatMenu.objects.get(handle=menu_handle)
            items = menu.get_top_level_items()
            
        except Exception:
            pass
        if items:
            for item in items:
               handleSub = "navigation-" + (item.menu_text) 
               menuItems.append({
                    'href': item.relative_url(),
                    'label': item.menu_text,
                    'desc': item.hover_description,
                    'openInNewWindow': item.open_in_new_window,
                    'children': self.get_menu_items(handleSub)
                })

        return menuItems

    def get_nav_api_representation(self):

        return {
                'contact_page_url': self.contact_page_url,
                'search_page_url': self.search_page_url,
                'mainMenuItems': self.get_menu_items('navigation-main'),
        }
    
    def get_nav_json_representation(self):

        return json.dumps(self.get_nav_api_representation())

**Wagtail_admin_page:**

![image](https://user-images.githubusercontent.com/67430585/85980345-d637c680-b9ff-11ea-9fea-55656a72305b.png)


**Home page:**

![image](https://user-images.githubusercontent.com/67430585/85980419-fc5d6680-b9ff-11ea-9a34-e42d4d0f8c37.png)



@ababic : please let me know if you need more details

**Comment by ababic** [comment]
@shinchan28 It's always a bad idea to do `except Exception:` what do you get if you remove that from your `get_menu_items()` function/method? I imagine it will tell you that `._contextual_vals` or `._option_vals` haven't been set?

Menus are supposed to be rendered from the template tags included in the project, where these values are set as part of the process.

**Comment by ababic** [comment]
@shinchan28 Also, if you're going to use flat menus to define your 'main' menus (as your screenshot suggests), you should:
- Remove any custom 'MainMenu' models
- Add `WAGTAILMENUS_MAIN_MENUS_EDITABLE_IN_WAGTAILADMIN = False` to your project settings
- Only use the `{% flat_menu %}` tag in templates to render menus

**Comment by shinchan28** [comment]
@ababic i am sorry. i am new to wagtail and i am trying to understand this code as well. This seems to be a bit complex for me as it is using the package functions. This header has been linked to the Footer. Kindly i need your advice to render the values.

**Comment by shinchan28** [comment]
@ababic i'll try as you suggested .

**Comment by ababic** [comment]
@shinchan28 And if you are only overriding a single existing field on `CustomFlatMenu` (which is already included in the `content_panels` on the `AbstractFlatMenu` class), you don't have to redefine `content_panels` for your model - you can remove those lines and save yourself the ongoing maintenance burden.

**Comment by shinchan28** [comment]
@ababic : it is working now .. thank you so much

**Comment by ababic** [comment]
Thanks @shinchan28. Glad you managed to get things sorted. I'll leave this issue open for now, as I'm not 100% sure you had the same issue as the other reporters.

**Comment by mochajazz** [comment]
Im having a similar issue. I thought it was the WT version i was using, so started again going back to wagtail version 2.9, and it will only render custom menu items, and NOT any internal page menu items

**Comment by JoeWHoward** [comment]
Having the same problem here.  My menu_items list is empty, but the template I have at templates/menus/main/menu.html is loading in.

**Comment by ababic** [comment]
@mochajazz / @JoeWHoward Are you 100% sure both `show_in_menus` and `live` are `True` for the pages you are expecting to appear?

**Comment by ababic** [comment]
I suspect there could be a conditional somewhere that is expecting a list (which is 'falsey' when empty) but is instead receiving a generator. However, I can't see why the Wagtail or Django version would make a difference there. This would really benefit from a little investigation by someone experiencing the issue... E.g. Adding a custom menu class with print statements indicating the state/types of objects at different points in the process, or even writing a tag to output type and state data in templates. I would have fixed it by now if I knew how to recreate, but need a lot more to go on unfortunately. And please please please share versions where possible.

**Comment by JoeWHoward** [comment]
@ababic Using Wagtail 2.11.3 and Django 3.1.2, I am now trying to implement a custom menu class for debugging (from your comment above on June 28) but I don't know where to set breakpoints to access menu_items (or where the list of menu items is being generated).  I am down to try to tackle this, but will need some guidance on how to go about chasing down the issue.

I've joined the Google support group, if you have otherwise a Slack or Discord I would be open to communicating through there.  I will keep playing around with it and try to find some answers for us both.

**Comment by ababic** [comment]
@JoeWHoward thanks so much!

First of all, it's worth trying different option combinations on the menu tag to see if they make a difference.

Second, have a browse at the source code for the original menu classes. The various class and instance methods involved in the process should all have docstrings explaining what they do, and are arranged roughly in execution order.

For main menus, first look for methods that make queries for pages and menu items... Try overriding these and printing querysets to check if they look correct early on in the process. This should help you figure out whether it's a problem with your data, or a problem with the query logic. From there, you can try overriding the querysets to see which filters make a difference to the result.

If that doesn't identify the problem, you can direct message me on Slack (I'm on the Wagtail one), and we can figure out where to go from there?

**Comment by ababic** [comment]
@JoeWHoward Happy new year! May I ask how your investigation went? Did you find the cause of the issue in your project?

**Comment by rob101** [comment]
FYI, I found this error occurs when you are calling `{{ menu_items }}` directly, without invoking it through a template in `{% main_menu template=...%}`

**Comment by confuzeus** [comment]
For some reason, I haven't been able to replicate this issue at all since I opened this.

I doubt calling `{{ menu_items }}` directly is the issue because the context should already have been populated with the `menu_items` key. The issue might be in the code that populates the context.

Until I'm able to replicate this, I'll allow someone else to carry out investigations.

**Comment by ababic** [comment]
Personally, I think this issue should be closed, as there is not nearly enough information here to reproduce the issue. Please may I remind folks that this app is maintained entirely be volunteers (for free), none of whom are magical creatures who somehow know how you are using the app :) Please try to imagine all the information you'd need if you yourself were tasked with recreating/fixing the problem, and provide that level of information.

**Comment by confuzeus** [comment]
Good idea. I closed it before but it reopened somehow.
