### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by SteinRobert** [jazzband/wagtailmenus#398]
Any plans on when the next release is going to happen?

I've got a few failing test cases with the latest version (3.0.2 - #380).
Bumping to the latest commit (b0a6acb281227c93b3b4f11265366da0dada4248) does help, however that forces me to install git in my Docker image.

Happy to help, if you need any support.

**Comment by ababic** [comment]
Hi @SteinRobert. Andy here, the original author of wagtailmenus. I'm afraid I'm just too busy with client work these days to regularly maintain this. When I actually worked at RKH, we used this for every project, but it's not as popular at Torchbox, so it's not getting the attention it needs.

Secondary to the above issues, there's the weird political aspect of me continuing to work on something in my ex-employers account. I naively hoped they would invest in it after I moved on, but that has not happened.

I suppose I could treat my personal fork as the canonical version and leave this one in the dust, but that feels like a bit of a 'slap in the face' to my ex employer. I suppose if someone else wanted to take the reigns (in their own fork), that wouldn't be so bad (it IS open-source after all).
