### ISSUE TITLE
Will there be any updates in the near future?

### ISSUE THREAD

**Issue by matacino** [jazzband/wagtailmenus#402]
Hi,

firstly: Thank you for the handy "wagtailmenus". 

But at the moment this wagtail-extension becomes a cause for potential security riscs because one can't/don't want to upgrade wagtail because of:

`RemovedInWagtail211Warning: wagtail.core.middleware.SiteMiddleware and the use of request.site is deprecated. Please update your code to use Site.find_for_request(request) in place of request.site, and remove wagtail.core.middleware.SiteMiddleware from MIDDLEWARE
  warnings.warn(`

Is SiteMiddleware realy necessary?

**Comment by sowinski** [comment]
Fixing this problem looks quite easy. If the repo owner reads this. I can provide a commit if you will check and upload it afterwards.

**Comment by matacino** [comment]
@sowinski I found your fork at https://github.com/sowinski/wagtailmenus - did you/could you do a commit with the fix?

**Comment by sowinski** [comment]
I used @MrCordeiro fork.
https://github.com/rkhleics/wagtailmenus/issues/403

Is this working for you?
https://github.com/rkhleics/wagtailmenus/pull/404

Which Django version do you use currently?

**Comment by MrCordeiro** [comment]
Hey @matacino and @sowinski. Now we moved the package to Jazzband, we can close this issue, no?

**Comment by sowinski** [comment]
@MrCordeiro 
I have seen that the moved the package a few weeks ago. But there is still no update, correct?

**Comment by MrCordeiro** [comment]
@sowinski, it's not yet 100% moved. Issue #409 must be completed first.

**Comment by matacino** [comment]
After I could spare some time for analyzing the source code, I discovered, that the source code actually deals with the Problem in that way that it tolerates the absence of "SiteMiddleware" in falling back (or forth) to the wagtailmenus.utils get_site_from_request():

```
from wagtail.core.models import Page, Site
…
from wagtailmenus.utils.misc import get_fake_request, get_site_from_request
…
class Menu:
…
    @classmethod
    def _get_site(cls, context):
        site = context.get('site')
        if isinstance(site, Site):
            return site
        request = context.get('request')
        if request is not None:
            return get_site_from_request(request)
…
```

So "it works for me"™© but the documentation should be adapted to a new world without SiteMiddleware.
