### ISSUE TITLE
Django 4.0 compatibility

### ISSUE THREAD

**Issue by MrCordeiro** [jazzband/wagtailmenus#403]
This package should be ready to support Django 4.0 as well as drop support for unsupported Django versions.

**Comment by sowinski** [comment]
Unfortunately maintenance of this project stopped.

**Comment by MrCordeiro** [comment]
@sowinski I was planning to add a PR myself, as the contributing guide says it's the preferred way of submitting PR.

**Comment by sowinski** [comment]
@MrCordeiro This would be awesome.

**Comment by sowinski** [comment]
@MrCordeiro Can you take over this repository or can you just do a fork called wagtailmenus2.0 and publishing a pip package? :)

**Comment by MrCordeiro** [comment]
@sowinski, I got in contact with the company that owns this package and they told me they were evaluating how to proceed with it's maintenance.

I don't like the idea of forking a V2. It's too confusing for users; I would only use as a last case scenario.

I don't have the advanced knowledge of Wagtail to properly maintain it, so I could only take over temporarily. Ideally, the project could be transferred to a python group like Jazzband (or a equivalent group focused on Wagtail) that maintains projects such as this.

**Comment by sowinski** [comment]
@MrCordeiro Thank you for taking here. Pleae keep us up to date :)

Hopefully they will answer soon. I would like to move further to a newer Wagtail and Also newer Django version. **Django 2.2 LTS supports ends in April 2022**

**Comment by sowinski** [comment]
@MrCordeiro 
> I don't like the idea of forking a V2. It's too confusing for users; I would only use as a last case scenario.
When is your deadline for publishing Version 2.0 :)

**Comment by MrCordeiro** [comment]
> @MrCordeiro
> 
> When is your deadline for publishing Version 2.0 :)

@sowinski, just gave them a nudge last week. Let's give a month? What do you think?

**Comment by MrCordeiro** [comment]
We have to update the project's compatibility list. I'm thinking:

- removing Python 3.4, 3.5, and 3.6 which no longer have support
- adding Python 3.9 and 3.10
- dropping Django 1.11 (also, no support)
- adding Django 4 (obviously)

**Comment by sowinski** [comment]
> @sowinski, just gave them a nudge last week. Let's give a month? What do you think?

Fork? :) I think Jazzband is not interested to do something here. 
I have no experience with packages on github. But if you have some experience I can help with tests and a CI pipeline.

**Comment by aliceni81** [comment]
Have been waiting for the new release with Django 4.0 compatibility..

**Comment by tonykyriakidis** [comment]
Any updates on this? @MrCordeiro

**Comment by MrCordeiro** [comment]
wagtailmenus v3+ has Django 4 support ^_ ^
