### ISSUE TITLE
Publish 3.1 release on GitHub and PyPI

### ISSUE THREAD

**Issue by brylie** [jazzband/wagtailmenus#419]
Currently, version `3.0.2` is the latest wagtailmenus release on GitHub and PyPI. Please remember to publish the [`3.1` release](https://github.com/jazzband/wagtailmenus/blob/master/CHANGELOG.md#31-12022022) on GitHub and PyPI, even if it is only a ceremonial release :-)

- https://pypi.org/project/wagtailmenus/#history
- https://github.com/jazzband/wagtailmenus/releases

**Comment by sowinski** [comment]
I think this is not going to happen because of this "issue":
https://github.com/jazzband/wagtailmenus/issues/409

**Comment by naglis** [comment]
Hi, will the new releases ([3.1.0](https://github.com/jazzband/wagtailmenus/releases/tag/v3.1), [3.1.1](https://github.com/jazzband/wagtailmenus/releases/tag/v3.1.1)) be published on Pypi? :blush:

**Comment by sowinski** [comment]
Can someone explain where the next challenge is to publish the new version to PyPi?

I guess the new project maintainer need some kind of access rights for PyPI?

**Comment by martey** [comment]
See https://github.com/jazzband/help/issues/280 - the release workflow that uploads to PyPI is currently failing with an error.

**Comment by jezdez** [comment]
As requested in https://github.com/jazzband/wagtailmenus/issues/409 we're looking for a project lead to be able to verify and confirm when releases happen. That project lead hasn't been found so far.

**Comment by craigds** [comment]
jazzband/help#280 implies that the release has been published, but it hasn't - [pypi still doesn't have a 3.1.x release](https://pypi.org/project/wagtailmenus/) and this is still blocking adoption of Django 4.x

**Comment by Redjam** [comment]
Is it possible to push 3.1 version at least as a release candidate?

**Comment by sowinski** [comment]
What is the problem right now?

**Comment by jezdez** [comment]
This will most likely be closed by #425 now that #409 is closed.
