### ISSUE TITLE
 Publish 3.1.2 release on GitHub and PyPI #419 

### ISSUE THREAD

**Issue by pragnyad** [jazzband/wagtailmenus#425]

**Comment by sowinski** [comment]
What is the current status? :)

**Comment by xavitorne** [comment]
same here, when do you think the publish could be possible? thanks

**Comment by sowinski** [comment]
Is it possible to install this package over pip?

I tried this:
```
pip3 install git+https://github.com/jazzband/wagtailmenus@releases/tag/v3.1.2#egg=wagtailmenus
Collecting wagtailmenus
  Cloning https://github.com/jazzband/wagtailmenus (to revision releases/tag/v3.1.2) to /tmp/pip-install-3c8e55qq/wagtailmenus_072bc634173b434f994c3fe2e71ef2c7
  Running command git clone --filter=blob:none -q https://github.com/jazzband/wagtailmenus /tmp/pip-install-3c8e55qq/wagtailmenus_072bc634173b434f994c3fe2e71ef2c7
  WARNING: Did not find branch or tag 'releases/tag/v3.1.2', assuming revision or ref.
  Running command git checkout -q releases/tag/v3.1.2
  error: pathspec 'releases/tag/v3.1.2' did not match any file(s) known to git
WARNING: Discarding git+https://github.com/jazzband/wagtailmenus@releases/tag/v3.1.2#egg=wagtailmenus. Command errored out with exit status 1: git checkout -q releases/tag/v3.1.2 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement wagtailmenus (unavailable) (from versions: 0.2.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.5rc1, 2.5, 2.5.1, 2.5.2, 2.6, 2.7, 2.7.1, 2.8, 2.9, 2.10, 2.10.1, 2.11, 2.11.1, 2.12, 2.12.1, 2.13, 2.13.1, 3.0, 3.0.1, 3.0.2)
ERROR: No matching distribution found for wagtailmenus (unavailable)
WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
You should consider upgrading via the '/home/myhome/git/myvenv/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by xavitorne** [comment]
> Is it possible to install this package over pip?
> 
> I tried this:
> 
> ```
> pip3 install git+https://github.com/jazzband/wagtailmenus@releases/tag/v3.1.2#egg=wagtailmenus
> Collecting wagtailmenus
>   Cloning https://github.com/jazzband/wagtailmenus (to revision releases/tag/v3.1.2) to /tmp/pip-install-3c8e55qq/wagtailmenus_072bc634173b434f994c3fe2e71ef2c7
>   Running command git clone --filter=blob:none -q https://github.com/jazzband/wagtailmenus /tmp/pip-install-3c8e55qq/wagtailmenus_072bc634173b434f994c3fe2e71ef2c7
>   WARNING: Did not find branch or tag 'releases/tag/v3.1.2', assuming revision or ref.
>   Running command git checkout -q releases/tag/v3.1.2
>   error: pathspec 'releases/tag/v3.1.2' did not match any file(s) known to git
> WARNING: Discarding git+https://github.com/jazzband/wagtailmenus@releases/tag/v3.1.2#egg=wagtailmenus. Command errored out with exit status 1: git checkout -q releases/tag/v3.1.2 Check the logs for full command output.
> ERROR: Could not find a version that satisfies the requirement wagtailmenus (unavailable) (from versions: 0.2.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.5rc1, 2.5, 2.5.1, 2.5.2, 2.6, 2.7, 2.7.1, 2.8, 2.9, 2.10, 2.10.1, 2.11, 2.11.1, 2.12, 2.12.1, 2.13, 2.13.1, 3.0, 3.0.1, 3.0.2)
> ERROR: No matching distribution found for wagtailmenus (unavailable)
> WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
> You should consider upgrading via the '/home/myhome/git/myvenv/bin/python3 -m pip install --upgrade pip' command.
> ```

Yes, you can install with the zip file:
pip install https://github.com/jazzband/wagtailmenus/archive/refs/tags/v3.1.2.zip

**Comment by nxmyoz** [comment]
You can put something like this in the requirements.txt or similar file:

`wagtailmenus @ https://github.com/jazzband/wagtailmenus/archive/refs/tags/v3.1.2.tar.gz`

**Comment by MrCordeiro** [comment]
I'm sick of waiting for #409 to close in order to have a proper release.

I tried contacting @jezdez via GitHub issues and email, with no responses.

The only time I got a reply out of him was  complained on Twitter (and even then he got defensive).

I feel super guilty for convincing the original maintainer to move to Jazzband. I just have asked them to transfer it to me directly instead.

With the launch of Django 4.1, my projects are collecting tech debt to a point I can no longer afford. So I'm considering just forking this project and publishing it on PyPi on my own. Would that be too bad?

**Comment by sowinski** [comment]
Please do this. Jazzband seems to be dead.

**Comment by jezdez** [comment]
> I'm sick of waiting for #409 to close in order to have a proper release.

Please be so kind and reflect on what you're saying here, you're "sick" about waiting on volunteers to do something for you. That's really not an appropriate way to communicate here. I get your frustration, of course, but you must realize that nobody here works for you.

Plus, the timeline in https://github.com/jazzband/wagtailmenus/issues/409 doesn't support your impatience, the transfer to Jazzband hadn't even been finished yet (the project lead question was still open). I only get to responding to the request now, not really complicated.

> I tried contacting @jezdez via GitHub issues and email, with no responses.

True, I'm sorry for having not responded so far, life just keeps happening and my spare time is limited. Circling back to the transfer request in https://github.com/jazzband/wagtailmenus/issues/409 is on my TODO list and your words here made it jump to the top.

> The only time I got a reply out of him was when I complained about Jazzband on Twitter (and even then he got defensive).

No need to talk about me in the 3rd person, I get defensive when unreasonable expectations are voiced publicly.

The latest state of the world was that I asked you to decide who would be the project lead for the project, to finalize the transfer to Jazzband, and you responded on June 1 (4 months after initial transfer): https://github.com/jazzband/wagtailmenus/issues/409#issuecomment-1143857204.

FWIW I have to say that I'm on the fence of making you project lead now given the lack of conduct you've shown here though. When contributing to Jazzband projects you're agreeing to follow its [Code of Conduct](https://jazzband.co/about/conduct), I encourage you to review it again.

> I feel super guilty for convincing the original maintainer to move to Jazzband. I should have asked them to transfer it to me directly instead.

Sure, transfer is still an option to be clear, Jazzband isn't a prison, assuming the original author @ababic agrees.

> With the launch of Django 4.1, my projects are collecting tech debt to a point I can no longer afford. So I'm considering just forking this project and publishing it on PyPi on my own. Would that be too bad?

I'm sorry, but that's not realistic, the transfer of the project to Jazzband [happened on February 1 2022](https://github.com/jazzband/wagtailmenus/issues/409), with the final decision who project lead is [happening on June 1](https://github.com/jazzband/wagtailmenus/issues/409#issuecomment-1143857204), hardly a long time on a larger scope to call this to be an issue of tech debt.

**Comment by jezdez** [comment]
> Please do this. Jazzband seems to be dead.

Come on, that's way out of line @sowinski.

**Comment by jezdez** [comment]
Now with #409 closed (@MrCordeiro and @schlich have volunteered as project leads) this ticket can be handled by the project leads.

@MrCordeiro @schlich I've resent the release notifications to you about the pending releases as shown (for you) on https://jazzband.co/projects/wagtailmenus. Please follow the instructions in them.

**Comment by schlich** [comment]
Thank you @jezdez for following up on this.  I will be merging tonight after review.

**Comment by schlich** [comment]
Go forth and prosper, friends.  Will go over existing PRs asap.
