### ISSUE TITLE
Potential UI compatibility issues with Wagtail 4.0

### ISSUE THREAD

**Issue by thibaudcolas** [jazzband/wagtailmenus#428]
👋 as part of the Wagtail 4.0 release, we’ve reviewed [potential breaking changes in UI customisations](https://wagtail.org/blog/wagtail-216-and-upcoming-breaking-changes/) in community packages.

I have identified two issues in wagtailmenus that will likely need looking into.

## Legacy fields markup in stylesheets

A lot of the styles in [menu-edit.css](https://github.com/jazzband/wagtailmenus/blob/master/wagtailmenus/static/wagtailmenus/css/menu-edit.css) rely on markup which we have removed. All of those styles will likely need to be completely recreated for the new UI – but I would suggest considering removing them altogether, as they likely were implemented to solve issues that aren’t relevant anymore.

## Editor CSS loading

We removed the need for separate loading of editor CSS. Editor CSS is now loaded everywhere. In [mainmenu_edit.html](https://github.com/jazzband/wagtailmenus/blob/master/wagtailmenus/templates/wagtailmenus/mainmenu_edit.html), the include of `_editor_css.html` can be removed.

---

See our [full analysis](https://gist.github.com/thibaudcolas/b6341dcb51e648fe24d781798c598661) for other patterns we reviewed (and didn’t find matching issues) in this package, and consider joining [#package-maintainers on the Wagtail Slack](https://github.com/wagtail/wagtail/wiki/slack) if you’re interested in collaborating with other Wagtail package maintainers.

**Comment by nutjob4life** [comment]
Woot, thanks @thibaudcolas! This is some great research.

**Comment by uroybd** [comment]
> Woot, thanks @thibaudcolas! This is some great research.
> 
> I tried my own overriding template that removed `_editor_css.html` but that just produced a scarier looking stacktrace:
> 
> ```
> Traceback (most recent call last):
>   File "django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>   File "django/core/handlers/base.py", line 220, in _get_response
>     response = response.render()
> …
>   File "django/template/defaulttags.py", line 151, in render
>     first = render_value_in_context(value, context)
>   File "django/template/base.py", line 1047, in render_value_in_context
>     value = str(value)
> TypeError: __str__ returned non-string (type __proxy__)
> ```
> 
> but as a non-Django, non-Wagtail, non-Wagtailmenus person I thought I better leave well enough alone for now relaxed

I tried overriding. It works just fine.

**Comment by uroybd** [comment]
> Hi uroybd, I'm sorry I'm a newbie at this, would you be able to explain for someone like myself exactly what you did to get this to work? If you can I guess others will be grateful too.

1. In your project's (or any of the app's) `templates` folder, create a `wagtailmenus` folder.
2. Then create the `mainmenu_edit.html` file there with following content:

```html
{% extends "modeladmin/create.html" %}

{% block extra_css %}
    {% comment %} {% include "wagtailadmin/pages/_editor_css.html" %} {% endcomment %}
    {{ edit_handler.form.media.css }}
    {{ view.media.css }}
{% endblock %}

{% block extra_js %}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ edit_handler.form.media.js }}
    {{ edit_handler.html_declarations }}
    {{ view.media.js }}
{% endblock %}

{% block header %}
    {% include "wagtailmenus/includes/header_with_site_switcher.html" with title=view.page_title subtitle=view.get_page_subtitle icon=view.header_icon %}
{% endblock %}

{% block form_action %}?{% endblock %}
```
That's it.

It should be recognized right away. If not, just restart the server.

**Comment by churcht** [comment]
Thanks uroybd, I really appreciate your help.  

For the record, I'm using wagatil 4.0.1 on django 4.1, wagtailmenus 3.1.2

The recommended change has resolved the original error, which was:
"error at line 4" of env/bin/lib/python3.8/site-packages/wagtailmenus/templates/wagtailmenus/mainmenu_edit.html

Unfortunately I have a new one to take its place.

TypeError at /admin/wagtailmenus/mainmenu/edit/1/
__str__ returned non-string (type __proxy__)

I guess this isn't the right forum to resolve this type of error, so I'll leave the discussion here and post a question elsewhere.

Thanks again.

**Comment by churcht** [comment]
Correction: django 4.1.1 newbie error ;)

**Comment by nutjob4life** [comment]
Thanks for the sanity-check, @uroybd: that was precisely what I did: made my own `mainmenu_edit.html` and commented-out the inclusion of `wagtailadmin/pages/_editor_css.html`.

But the results were vastly different: the 225 line-long stack trace I mentioned above ending with the same error that @churcht saw. (I'm also using Django 4.1.1, Wagtail 4.0.1, and Wagtailmenus 3.1.2.) Oh well! 🤷‍♀️

**Comment by ArnarTumi** [comment]
Yeah, as far as I could see the problem is with the helptext on the maximum levels field. When field.py in wagtail tries to render the field it tries to cast this helptext to string but because it is lazy translated field it returns a proxy object instead of a string. I didn't find any good ways to override this except to override fields.py and remove the helptext part which then would remove helptexts for all fields in the admin interface... not really a useful solution.

**Comment by perepicornell** [comment]
@churcht, @nutjob4life if you find a solution please let us know, I'm facing exactly the same issue when applying the workaround, whern upgraded to Django 4.1.1 and Wagtail 4.0.1.
Many thanks in advance :)

**Comment by jnpkr** [comment]
> 

This seems to be caused in Django >= 4.1 with the [change of `mark_safe` behaviour ](https://docs.djangoproject.com/en/4.1/releases/4.1/#utilities)

I changed the two instances of `mark_safe_lazy` in `wagtailmenus/models/menus.py` to `mark_safe` and I don't get any errors now

I'm using Wagtail 4.0.1 and Django 4.1.1

**Comment by churcht** [comment]
Making the changes described by @jnpkr fixed the problem for me too. Many thanks.

**Comment by Iomys** [comment]
I had the same issues and the changes described by @jnpkr ([this](#issuecomment-1255606076)) and @uroybd ([this](#issuecomment-1251781375)) worked for me. Thanks

**Comment by janbaykara** [comment]
> > Hi uroybd, I'm sorry I'm a newbie at this, would you be able to explain for someone like myself exactly what you did to get this to work? If you can I guess others will be grateful too.
> 
> 1. In your project's (or any of the app's) `templates` folder, create a `wagtailmenus` folder.
> 2. Then create the `mainmenu_edit.html` file there with following content:
> 
> ```
> {% extends "modeladmin/create.html" %}
> 
> {% block extra_css %}
>     {% comment %} {% include "wagtailadmin/pages/_editor_css.html" %} {% endcomment %}
>     {{ edit_handler.form.media.css }}
>     {{ view.media.css }}
> {% endblock %}
> 
> {% block extra_js %}
>     {% include "wagtailadmin/pages/_editor_js.html" %}
>     {{ edit_handler.form.media.js }}
>     {{ edit_handler.html_declarations }}
>     {{ view.media.js }}
> {% endblock %}
> 
> {% block header %}
>     {% include "wagtailmenus/includes/header_with_site_switcher.html" with title=view.page_title subtitle=view.get_page_subtitle icon=view.header_icon %}
> {% endblock %}
> 
> {% block form_action %}?{% endblock %}
> ```
> 
> That's it.
> 
> It should be recognized right away. If not, just restart the server.

Hey @uroybd, would you be willing to submit a quick PR for this?

**Comment by janbaykara** [comment]
I wonder if this can be closed?

**Comment by schlich** [comment]
Is there still an error or is there a corresponding PR?

**Comment by uroybd** [comment]
It has been solved.

**Comment by nutjob4life** [comment]
Thanks for this everyone! I've switched over my requirements to the PyPI release of 3.1.3 and things work great 🥳
