### ISSUE TITLE
Discrepancy between compatibility on website and readme.

### ISSUE THREAD

**Issue by dino8890** [jazzband/wagtailmenus#445]
Hi, documentation website says this package is not compatible with never versions of Django and Wagtail, but in reality it is and the readme file reflects this. This might turn off new users who don't bother to look at the repository so I think it is important to address this. Let me know if you want me to submit a PR!

**Comment by schlich** [comment]
A PR would be appreciated! Docs could use some tidying up in general,
thanks for bringing this up!

**Comment by MrCordeiro** [comment]
@dino8890, if you could point out the exact location of the misleading information, that would help a lot. Thanks!

**Comment by MaartenUreel** [comment]
First paragraph of the first page you get when searching for this project :)

https://wagtailmenus.readthedocs.io/en/stable/


> Wagtail versions 2.0 to 2.10
> Django versions 1.11, 2.0, 2.2 and 3.0
> Python versions 3.4 to 3.8
