### ISSUE TITLE
Does not work with Wagtail 5.1

### ISSUE THREAD

**Issue by frague59** [jazzband/wagtailmenus#460]
Hi,
I'm starting a brand new project with wagtail 5.1, and I need menus !

AFAIK, wagtail menus does not support templates name schemas used by wagtail 5.1.

For example, when I try to create a new main menu item, I've an issue with templates:
```
<h1>TemplateDoesNotExist
       at /admin/wagtailmenus/mainmenu/edit/2/</h1>
  <pre class="exception_value">modeladmin/create.html</pre>
  

Request Method: | GET
-- | --
http://localhost:8000/admin/wagtailmenus/mainmenu/edit/2/
3.2.20
TemplateDoesNotExist
modeladmin/create.html
/home/fguerin/Projects/lecanal.tourcoing.fr/intranet/venv/lib/python3.9/site-packages/django/template/backends/django.py, line 84, in reraise
/home/fguerin/Projects/lecanal.tourcoing.fr/intranet/venv/bin/python
3.9.16
['/home/fguerin/Projects/lecanal.tourcoing.fr/intranet/src',  '/home/fguerin/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/232.9559.58/plugins/python/helpers/pydev',  '/home/fguerin/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/232.9559.58/plugins/python/helpers/third_party/thriftpy',  '/home/fguerin/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/232.9559.58/plugins/python/helpers/pydev',  '/home/fguerin/Projects/lecanal.tourcoing.fr/intranet',  '/home/fguerin/Projects/lecanal.tourcoing.fr/intranet/src',  '/home/fguerin/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/232.9559.58/plugins/python/helpers/pycharm_display',  '/home/fguerin/.cache/JetBrains/PyCharm2023.2/cythonExtensions',  '/usr/local/lib/python39.zip',  '/usr/local/lib/python3.9',  '/usr/local/lib/python3.9/lib-dynload',  '/home/fguerin/Projects/lecanal.tourcoing.fr/intranet/venv/lib/python3.9/site-packages',  '/home/fguerin/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/232.9559.58/plugins/python/helpers/pycharm_matplotlib_backend']
Mon, 11 Sep 2023 17:25:25 +0200
```

Could I fix it and provide a PR ? 

Thanks !

**Comment by MrCordeiro** [comment]
Yes, that would be awesome, @frague59 !

It will also take a load out of my back 🙂

Please don't forget to read the [Contributing guidelines](https://wagtailmenus.readthedocs.io/en/stable/contributing/index.html#contributing-code-changes-via-pull-requests). I look forward to your PR!

My suggestion is: start by adding Wagtail 5.1 to the `tox` setup and checking the tests that fail.

**Comment by MatthewStuart1994** [comment]
Did you add `'wagtail.contrib.modeladmin'` to the list of installed apps?

```
INSTALLED_APPS = [
    ...
    'wagtail.contrib.modeladmin',  # Don't repeat if it's there already
    'wagtailmenus',
]
```

This error is seen when you remove `'wagtail.contrib.modeladmin'` from the installed apps.

I have this working in `wagtail==5.1.1`

**Comment by frague59** [comment]
https://github.com/jazzband/wagtailmenus/issues/459

**Comment by DatCGI2net** [comment]
> I have this working in `wagtail==5.1.1`
Are you sure? I have just seen this note:
https://docs.wagtail.org/en/latest/releases/5.1.html#wagtail-contrib-modeladmin-is-deprecated

**Comment by dkirkham** [comment]
As per @MatthewStuart1994's comment, Wagtailmenus and some of my other Wagtail ModelAdmin code works fine in Wagtail 5.1.1, the only issue is the logging of the deprecation messages - ModelAdmin will be removed in Wagtail 6.

**Comment by MrCordeiro** [comment]
Now #461 has been merged, I think we can close this one. Nice work, @dkirkham !

We can leave #459 open until we finally migrate to model snippets.
