### ISSUE TITLE
Update documentation for new release

### ISSUE THREAD

**Issue by schlich** [jazzband/wagtailmenus#476]
Follow-up issue from pr #472

> I tested `wagtailmenus` in one of my projects this evening, using both Wagtail 5.2 and Wagtail 6.0.1, and haven't detected any issues.
>
> I did however encounter an issue during installation, it seems installing from github didn't reliably remove and change all the package files. I found I had to:
> - `pip uninstall wagtailmenus`
> - `pip install git+https://github.com/dkirkham/wagtailmenus.git@migrate-modeladmin-snippets`
>
> If `wagtailmenus` is the last dependence you have on Wagtail ModelAdmin, then you can also remove it:
> - remove `wagtail_modeladmin` or `wagtail.contrib.modeladmin` from your `settings/base.py`
> - `pip uninstall wagtail_modeladmin`

_Originally posted by @dkirkham in https://github.com/jazzband/wagtailmenus/issues/472#issuecomment-1952400351_

**Comment by MrCordeiro** [comment]
> I did however encounter an issue during installation, it seems installing from github didn't reliably remove and change all the package files. I found I had to:
> 
> * `pip uninstall wagtailmenus`
> * `pip install git+https://github.com/dkirkham/wagtailmenus.git@migrate-modeladmin-snippets`

This feel more like an issue with pip, right?

**Comment by dkirkham** [comment]
I think it was a pip or local issue, I just mentioned it in case it was an issue for others testing before a proper release.
