### ISSUE TITLE
In Wagtail 6.1 not working menus!!

### ISSUE THREAD

**Issue by CARocha** [jazzband/wagtailmenus#491]
Hello, I try to be used with wagtail 6.1, but I get this error

https://pastebin.com/TF75hrDs

I used: 
Django 5.0.4
wagtail: 6.1

any help is welcome

thanks

**Comment by MrCordeiro** [comment]
@CARocha, this doesn't sound related to wagtailmenus. At least, there's no indication of that in the provided pastebin.

Can you provide more information?
