### ISSUE TITLE
wagtailmenus is dead?

### ISSUE THREAD

**Issue by nerdoc** [jazzband/wagtailmenus#492]
https://github.com/jazzband/wagtailmenus/issues/335#issuecomment-975425406

> Unfortunately this project is dead. No one is currently maintaining this package any more. 
> You should consider to avoid this package, because currently it is not supporting the newer wagtail versions..
> (Hopefully this changes soon)

Is this Project really dead? The comment was 2021, and there are still commits - just asking if I should use it or not...

**Comment by MrCordeiro** [comment]
Wagtailmenus is not in active development, but it is being maintained.

If you open an issue, we will to look into it. If you open a PR, we will review it and likely add it to the project.

But you have to bear in mind that we are unpaid maintainers. Sometimes life gets in the way, so we may not respond as quickly as you would like.

We certainly encourage the community to support this project with PRs and I would love to see yours someday! ❤️

With that said, I'm closing this issue.

**Comment by nerdoc** [comment]
Perfect, that's what I wanted to know. I am using it already, and who knows, maybe I can add something useful to it. Thanks for maintaining.
